// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ptsamonitor.Data;

#nullable disable

namespace ptsamonitor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502111957_AddAuditLogTable")]
    partial class AddAuditLogTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ptsamonitor.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Event")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("EVENT_NAME");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EVENT_DATE");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("NVARCHAR2(45)")
                        .HasColumnName("IP_ADDRESS");

                    b.Property<string>("PageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("PAGE_URL");

                    b.Property<int?>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.ToTable("PTSA_MONITOR_AUDIT_LOGS", "TADEYI");
                });

            modelBuilder.Entity("ptsamonitor.Models.Institution", b =>
                {
                    b.Property<int>("InstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("INSTITUTION_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstitutionId"));

                    b.Property<string>("BankBins")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("BANK_BINS");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("InstitutionCode")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("INSTITUTION_CODE");

                    b.Property<string>("InstitutionDomain")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("INSTITUTION_DOMAIN");

                    b.Property<string>("InstitutionEmails")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("INSTITUTION_EMAILS");

                    b.Property<string>("InstitutionLogo")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("INSTITUTION_LOGO");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("INSTITUTION_NAME");

                    b.Property<string>("InstitutionShortName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("INSTITUTION_SHORT_NAME");

                    b.Property<string>("InstitutionSubCodes")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("INSTITUTION_SUB_CODES");

                    b.Property<string>("InstitutionType")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("INSTITUTION_TYPE");

                    b.Property<string>("TerminalIds")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("TERMINAL_IDS");

                    b.HasKey("InstitutionId");

                    b.ToTable("PTSA_MONITOR_INSTITUTIONS", "TADEYI");
                });

            modelBuilder.Entity("ptsamonitor.Models.PtsaUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATION_DATE");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Institution")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("INSTITUTION");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LAST_LOGIN_DATE");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(45)
                        .HasColumnType("NVARCHAR2(45)")
                        .HasColumnName("LAST_LOGIN_IP");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Privileges")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("PRIVILEGES");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("USER_NAME");

                    b.Property<string>("UserType")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("USER_TYPE");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("PTSA_MONITOR_USERS", "TADEYI");
                });
#pragma warning restore 612, 618
        }
    }
}
